#!/bin/bash
################################################# Version 2 #####################
# Script to create cumulative logs of all CVE for a release
# Author : Naeem Khan
# Mentor Graphics Corporation

#Delete previous Log data
if [ -e reported_cve.txt ]; then
	rm reported_cve.txt
fi

if [ -e CVEFile.txt ]; then
        rm CVEFile.txt
fi

# Get all files with name isafw_cvelog | get lines with CVE- | remove pkg info: | sort | remove duplicate lines (if any) | Remove all Comma(s)
cat cve_accumulated.log | grep CVE- | awk '{gsub("pkg info: ", "");print}' | sort | uniq | tr -s ',' ' ' > CVEFile.txt

#Get one liner log in a varibale
CVE_LOG=`cat CVEFile.txt`
echo "cve data :"
echo "$CVE_LOG" 

#Format the log 
for word in $CVE_LOG; do
        if [[ ${word:0:1} == [[:lower:]] ]] ; then
		echo -n "$word " >> reported_cve.txt
	elif [[ ${word:0:1} == [:digit:] ]] ; then
		echo "$word"  >> reported_cve.txt
	else
		echo "$word"  >> reported_cve.txt
	fi
done
