#!/bin/bash
# Script to create cumulative logs of all CVE for a release
# Author : Naeem Khan
# Mentor Graphics Corporation

#Delete previous Log data
if [ -a cve_data.txt ]; then
	rm cve_data.txt
fi

if [ -a CVEFile.txt ]; then
        rm CVEFile.txt
fi

# Get all files with name isafw_cvelog | get lines with CVE- | remove pkg info: | sort | remove duplicate lines (if any) | Get everything on a line| Remove all Comma(s) | Remove repititions and write to file CVEFile.txt
cat isafw_cvelog* | grep CVE- | awk '{gsub("pkg info: ", "");print}' | sort | uniq | tr -s '\n' ' ' | tr -s ',' ' ' | awk '{ while(++i<=NF) printf (!a[$i]++) ? $i FS : ""; i=split("",a); print ""}' > CVEFile.txt

#Get one liner log in a varibale
CVE_LOG=`cat CVEFile.txt`
echo "cve data :"
echo "$CVE_LOG" 

#Format the log 
for word in $CVE_LOG; do
        if [[ ${word:0:1} == [[:lower:]] ]] ; then
		echo -n "$word " >> cve_data.txt
	elif [[ ${word:0:1} == [:digit:] ]] ; then
		echo "$word"  >> cve_data.txt
	else
		echo "$word"  >> cve_data.txt
	fi
done
